site_name: MIOM
theme:
    name: material
    custom_dir: docs/overrides
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        setup_commands:
        - import sys
        - sys.path.append("miom")
        selection:
          new_path_syntax: yes
    watch:
    - miom
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
extra:
  analytics:
    provider: google
    property: G-5SV6WE1KMZ
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js