site_name: MIOM
site_description: Mixed Integer Optimization for Metabolism
site_author: Pablo Rodriguez-Mier
site_url: https://metexplore.github.io/miom
repo_name: miom
repo_url: https://www.github.com/metexplore/miom
copyright: Copyright &copy; 2021 INRAE Toxalim
theme:
    name: material
    palette:
      primary: '#2e5c87'
    custom_dir: docs/overrides
plugins:
- search
- autorefs
- minify:
    minify_html: true
    htmlmin_opts:
        remove_comments: true
- mkdocstrings:
    handlers:
      python:
        setup_commands:
        - import sys
        - sys.path.append("miom")
        selection:
          new_path_syntax: yes
    watch:
    - miom
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
extra:
  analytics:
    provider: google
    property: G-5SV6WE1KMZ
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js