name: Deploy docs
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
          with:
            python-version: [3.9]
      - name: Deploy docs
        uses: pablormier/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXTRA_PACKAGES: build-base
